<?php

namespace KayStrobach\Wysiwyg\ViewHelpers\Widget;

use Neos\FluidAdaptor\Core\Widget\AbstractWidgetViewHelper;
use Neos\Flow\Annotations as Flow;


class WysiwygEditorViewHelper extends AbstractWidgetViewHelper
{

    /**
     * @Flow\Inject
     * @var \KayStrobach\Wysiwyg\ViewHelpers\Widget\Controller\WysiwygEditorController
     */
    protected $controller;

    public function initializeArguments()
    {
        parent::initializeArguments(); // TODO: Change the autogenerated stub
        $this->registerArgument('id', 'string', 'id attribute', false, '');
        $this->registerArgument('buttons', 'array', 'list of buttons', false, []);
    }

    /**
     * @return string
     * @throws \Exception
     */
    public function render()
    {
        return $this->initiateSubRequest();
    }
}
